services:
  nproxy:
    image: liberatti/nproxy:v1.0-alpha
    environment:
      MONGO_URI: mongodb://mongo
      NODE_ROLE: main
      NODE_KEY: dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "80:80"
      - "443:443"

  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local