services:
  nproxy:
    environment:
      MONGO_URI: mongodb://mongo/nproxy
      NODE_ROLE: main
      NODE_KEY: dev
    image: liberatti/nproxy:latest
    ports:
      - "5000:5000"
      - "80:80"
      - "443:443"

  nproxy2:
    environment:
      MONGO_URI: mongodb://mongo/nproxy
      CLUSTER_ENDPOINT: http://172.17.0.1:5000
      NODE_ROLE: replica
      NODE_KEY: dev
    image: liberatti/nproxy:latest
    ports:
      - "80:80"
      - "443:443"
  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local